services:
  api:
    container_name: api-dev
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    command: npm run dev